#!/usr/bin/env bash
set -x

autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place poetry_template_plugin --exclude=__init__.py
black poetry_template_plugin
isort --atomic poetry_template_plugin
